Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,4 +25,11 @@ jobs:
         run: mvn clean
       - name: Build with Maven
         run: mvn install -Dtest=JenkinsTest -Dheadless=set
+      - name: Test Reporter
+        uses: dorny/test-reporter@v1.5.0
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Run Tests            # Name of the check run which will be created
+          path: "**/surefire-reports/TEST-*.xml"    # Path to test results
+          reporter: java-junit    
       
